#!/usr/bin/python3
# This code write by Ms.nope
import os
import time
import sys
class color:
      green = '\033[92m'
      red = '\033[91m'
      End = '\033[0m'
      org = '\033[34m'
      darkblue = '\033[33m'
      blue = '\033[96m'
opt = color.org + """
┌──(Funny)""" + color.darkblue + """
└─/Choose """ + color.green + "$ " + color.End
def cls():
    os.system("clear")
def menu():
    os.system('printf "\033]2;Funny-Termux\a"')
    os.system("clear")
    print(color.green + """
 _____  __ __  ____   ____   __ __         ______    ___  ____   ___ ___  __ __  __ __ 
|     ||  |  ||    \ |    \ |  |  |       |      |  /  _]|    \ |   |   ||  |  ||  |  |
|   __||  |  ||  _  ||  _  ||  |  | _____ |      | /  [_ |  D  )| _   _ ||  |  ||  |  |
|  |_  |  |  ||  |  ||  |  ||  ~  ||     ||_|  |_||    _]|    / |  \_/  ||  |  ||_   _|
|   _] |  :  ||  |  ||  |  ||___, ||_____|  |  |  |   [_ |    \ |   |   ||  :  ||     |
|  |   |     ||  |  ||  |  ||     |         |  |  |     ||  .  \|   |   ||     ||  |  |
|__|    \__,_||__|__||__|__||____/          |__|  |_____||__|\_||___|___| \__,_||__|__|
                                                                                       """ + color.red + """
      (This code write by """ + color.blue + "Ms.nope" + color.red + " )" + color.End)
    print("\n1_figlet")
    print("2_toilet")
    print("3_cowsay")
    print("4_tty-clock")
    print("5_cmatrix")
    print("6_htop")
    print("7_neofetch")
    print("8_screenfetch")
    print("9_train")
    print("10_fire")
    print("11_Exit")
    choose = input(opt)
    if choose == '1':
      cls()
      os.system("sudo apt install figlet")
      time.sleep(1)
      fun()
    elif choose == '2':
        cls()
        os.system("sudo apt install toilet")
        time.sleep(1)
        fun2()
    elif choose == '3':
       cls()
       os.system("sudo apt install cowsay")
       time.sleep(1)
       fun3()
    elif choose == '4':
       cls()
       os.system("sudo apt install tty-clock")
       fun4()
    elif choose == '5':
       cls()
       os.system("sudo apt install cmatrix")
       fun5()
    elif choose == '6':
        cls()
        os.system("sudo apt install htop")
        fun6()
    elif choose == '7':
        cls()
        os.system("sudo apt install neofetch")
        fun7()
    elif choose == '8':
        cls()
        os.system("sudo apt install screenfetch")
        fun8()
    elif choose == '9':
        cls()
        os.system("sudo apt install sl")
        fun9()
    elif choose == '10':
        cls()
        os.system("sudo apt install cacafire")
        fun10()
    elif choose == '11':
        cls()
        print(color.green + "Exiting..." + color.End)
        exit(1)
    elif choose == '':
        menu()
    elif choose == ' ':
        menu()
    elif choose == '  ':
        menu()
    else:
        print(choose + color.org + " Not Found!" + color.End)
        time.sleep(2)
        menu() 
def fun():
   try1 = input("Do you want to make figlet? [y/n] ")
   if try1 == 'y':
     fig()
   elif try1 == 'n':
       try2()
   else:
       fun()
def try2():
    try3 = input("Do you want back to main menu? [y/n] ")
    if try3 == 'y':
      menu()
    elif try3 == 'n':
        cls()
        print(color.green + "Exiting..." + color.End)
        exit(1)
    else:
        try2()
def fig():
    try4 = input("Enter your word: ")
    time.sleep(2)
    os.system("figlet " + try4)
    time.sleep(1)
    try5 = input("Do you want to try again? [y/n] ")
    if try5 == 'y':
      fig()
    elif try5 == 'n':
        try2()
    else:
         fig()
def fun2():
    cls()
    os.system("sudo apt install toilet")
    time.sleep(1)
    try6()
def try6():
    try7 = input("Do you want to make toilet? [y/n] ")
    if try7 == 'y':
      try8()
    elif try7 == 'n':
        try9()
    else:
        try6()
def try8():
    try10 = input("Enter your word: ")
    time.sleep(1)
    os.system("toilet " + try10)
    try11()
def try11():
    try12 = input("Do you want to try again? [y/n] ")
    if try12 == 'y':
      try8()
    elif try12 == 'n':
        try2()
    else:
         try11()
def fun3():
    try13 = input("do you want make cowsay ? [y/n] ")
    if try13 == 'y':
      try14()
    elif try13 == 'n':
        try2()
    else:
        fun3()
def try14():
    try15 = input("Enter your word: ")
    time.sleep(1)
    os.system("cowsay " + try15)
    try16()
def try16():
    try17 = input("Do you want to try again? [y/n] ")
    if try17 == 'y':
      try14()
    elif try17 == 'n':
        try2()
    else:
        try16()
def fun4():
    try18 = input("Do you want to run tty-clock? [y/n] ")
    if try18 == 'y':
      try19()
    elif try18 == 'n':
        try2()
    else:
        fun4()
def try19():
    cls()
    os.system("tty-clock")
    try2()
def fun5():
    time.sleep(1)
    cls()
    os.system("cmatrix")
    try2()
def fun6():
    cls()
    os.system("htop")
    try2()
def fun7():
    cls()
    os.system("neofetch")
    try2()
def fun8():
    cls()
    os.system("screenfetch")
    try2()
def fun9():
    cls()
    os.system("sl")
    try20 = input("Do you want to try again? [y/n] ")
    if try20 == 'y':
      fun9()
    elif try20 == 'n':
        try2()
    else:
        fun9()
def fun10():
    cls()
    os.system("cacafire")
    try2()
def arg():
    if sys.argv[1] == '--install':
      try:
         os.system("sudo apt install " + sys.argv[2])
         print("Funny-Termux: Finish!")
         sys.exit()
      except KeyboardInterrupt:
            print("Funny-Termux: Error!")
            sys.exit()
    elif sys.argv[1] == '--help':
        print("""
arguments Command:
--help: help arguments!
--start: start funny-Termux menu!
--install + packet: Installing package!""")
    elif sys.argv[1] == '--start':
        menu()
    else:
        print(sys.argv[1] + color.red + " Arguments Command!\n" + color.End)
        print("")
        sys.exit()
if __name__ == '__main__':
  try:
     arg()
  except IndexError:
      print("""
--help: Arguments Command help!""")
      sys.exit()
# Funny-Termux
